/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mutasi;

import jabatan.FormJabatan;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import mainmenu.FormMenu;

/**
 *
 * @author afri
 */
public class FormMutasi extends javax.swing.JFrame {

    /**
     * Creates new form FormMutasi
     */
    Statement st;
    ResultSet rs;
    Connection con = Koneksi.getKoneksi();
    String MySQL = "SELECT * FROM mutasi";
    
    
    public FormMutasi() {
        initComponents();
        setData(MySQL);
        setAutoCB();
        setEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        btnCari2 = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKd = new javax.swing.JTextField();
        cbNIP = new javax.swing.JComboBox<>();
        cbNama = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbTempat = new javax.swing.JComboBox<>();
        cbRuangan = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTempat = new javax.swing.JTextField();
        txtRuang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 322, -1, -1));

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 322, 67, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 322, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pencarian", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        jPanel5.add(txtCari);

        btnCari2.setText("Cari");
        btnCari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnCari2);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 358, 645, -1));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 322, 67, -1));

        btnKembali.setText("Keluar");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 322, 67, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("FORM MUTASI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 38, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Kode Mutasi");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("NIP ");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nama");

        txtKd.setEditable(false);
        txtKd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdActionPerformed(evt);
            }
        });

        cbNIP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbNIP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", " " }));
        cbNIP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNIPItemStateChanged(evt);
            }
        });
        cbNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNIPActionPerformed(evt);
            }
        });

        cbNama.setEditable(true);
        cbNama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih NIP--", " " }));
        cbNama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNamaItemStateChanged(evt);
            }
        });
        cbNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamaActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Tempat");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Ruangan/Bagian");

        cbTempat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbTempat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih NIP--", " " }));
        cbTempat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTempatItemStateChanged(evt);
            }
        });
        cbTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTempatActionPerformed(evt);
            }
        });

        cbRuangan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbRuangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih NIP--", " " }));
        cbRuangan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRuanganItemStateChanged(evt);
            }
        });
        cbRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRuanganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKd, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(cbRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, -1, 210));

        jScrollPane6.setBackground(new java.awt.Color(0, 255, 255));

        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUserMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabelUser);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 410, 645, 153));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setForeground(new java.awt.Color(102, 204, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Tempat Mutasi");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Ruangan/Bagian");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("PEMINDAHAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTempat, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(txtRuang))
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel4)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        setSize(new java.awt.Dimension(686, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
     private void generateID() {
        String idDate = null;
        Date now = new Date();
        SimpleDateFormat df = new SimpleDateFormat("ddmmyyyyss");
        idDate = df.format(now);
        String phrase = "KDM";
        txtKd.setText(phrase + idDate);
    }
    
    private void setAutoCB(){
        try{
            String SQL = "SELECT * FROM jabatan";
            st = con.createStatement();
            rs = st.executeQuery(SQL);
            while(rs.next()){
                cbNIP.addItem(rs.getString("nip"));
                cbNama.addItem(rs.getString("nama_karyawan"));
                cbTempat.addItem(rs.getString("tempat"));
                cbRuangan.addItem(rs.getString("ruangan"));
            }
            rs.last();
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void setEmpty(){
        txtKd.setText("");
        cbNama.setSelectedItem("--Pilih NIP--");
        cbRuangan.setSelectedItem("--Pilih NIP--");
        cbTempat.setSelectedItem("--Pilih NIP--");
        txtTempat.setText("");
        txtRuang.setText("");
        cbNIP.setSelectedItem("--Pilih--");   
    }
    
    private void msgEmpty(){
        if (cbNIP.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "Pilih NIP");
            cbNIP.requestFocus();
        }else if (cbNIP.getSelectedItem().equals("--Pilih--")){
            JOptionPane.showMessageDialog(null, "Pilih NIP");
            cbNIP.requestFocus();
        }else if (cbNama.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "Pilih NIP");
            cbNIP.requestFocus();
        }else if (cbNama.getSelectedItem().equals("--Pilih NIP--")){
            JOptionPane.showMessageDialog(null, "Pilih NIP");
            cbNIP.requestFocus();
        }else if (txtTempat.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Tempat Mutasi Kosong");
            txtTempat.requestFocus();
        }else if (txtRuang.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Ruangan/Bagian Mutasi Kosong");
            txtRuang.requestFocus();
        }else if(cbTempat.getSelectedItem().equals("--Pilih NIP--")){
            JOptionPane.showMessageDialog(null, "Pilih NIP");
            cbNIP.requestFocus();
        }else if(cbTempat.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "Pilih NIP");
            cbNIP.requestFocus();
        }else if(cbRuangan.getSelectedItem().equals("--Pilih NIP--")){
            JOptionPane.showMessageDialog(null, "Pilih NIP");
            cbNIP.requestFocus();
        }else if(cbRuangan.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "Pilih NIP");
            cbNIP.requestFocus();
        }
    }
    
    private void setData(String SQL){
        try {
            st = con.createStatement();
            rs = st.executeQuery(SQL);
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("KODE MUTASI");
            model.addColumn("NIP");
            model.addColumn("NAMA");
            model.addColumn("TEMPAT");
            model.addColumn("RUANGAN");
            model.addColumn("TEMPAT MUTASI");
            model.addColumn("RUANGAN MUTASI");
            
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while(rs.next()){
                Object[] data = {
                  rs.getString("kode_mutasi"),
                  rs.getString("nip_karyawan"),
                  rs.getString("nama_karyawan"),
                  rs.getString("tempat_before"),
                  rs.getString("ruangan_before"),
                  rs.getString("tempat_after"),
                  rs.getString("ruangan_after")
                };
                model.addRow(data);
                tabelUser.setModel(model);
            }
        } catch (SQLException e){
            
        }
    }
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
                if (cbNIP.getSelectedItem().equals("") || cbNIP.getSelectedItem().equals("--Pilih--")|| cbNama.getSelectedItem().equals("")|| cbNama.getSelectedItem().equals("--Pilih NIP--")||txtTempat.getText().trim().equals("")|| txtRuang.getText().trim().equals("") || cbTempat.getSelectedItem().equals("") || cbTempat.getSelectedItem().equals("--Pilih NIP--") || cbRuangan.getSelectedItem().equals("") || cbRuangan.getSelectedItem().equals("--Pilih NIP--")) {
                    msgEmpty();
                } else {
                    generateID();
                    String SQL = "INSERT INTO mutasi VALUES ('" + txtKd.getText() + "','" + cbNIP.getSelectedItem() + "','" + cbNama.getSelectedItem() + "','" + cbTempat.getSelectedItem() + "','" + cbRuangan.getSelectedItem() + "','" + txtTempat.getText() + "','" + txtRuang.getText() + "')";
                    st.executeUpdate(SQL);
                    String SQLUp = "UPDATE jabatan SET tempat = '" + txtTempat.getText() + "', ruangan = '" + txtRuang.getText() + "' WHERE nip = '" + cbNIP.getSelectedItem() + "'";
                    st.executeUpdate(SQLUp);
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                    setEmpty();
                    setData(MySQL);
                }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            if (txtKd.getText().trim().equals("") ||cbNIP.getSelectedItem().equals("") || cbNIP.getSelectedItem().equals("--Pilih--")|| cbNama.getSelectedItem().equals("")|| cbNama.getSelectedItem().equals("--Pilih NIP--")||txtTempat.getText().trim().equals("")|| txtRuang.getText().trim().equals("") || cbTempat.getSelectedItem().equals("") || cbTempat.getSelectedItem().equals("--Pilih NIP--") || cbRuangan.getSelectedItem().equals("") || cbRuangan.getSelectedItem().equals("--Pilih NIP--")) {
                  msgEmpty();
            } else {
                String SQL = "UPDATE mutasi SET nip_karyawan = '" + cbNIP.getSelectedItem() + "', nama_karyawan = '" + cbNama.getSelectedItem() + "', tempat_before = '" + cbTempat.getSelectedItem() + "', ruangan_before = '" + cbRuangan.getSelectedItem() + "',tempat_after = '" + txtTempat.getText() + "',ruangan_after = '" + txtRuang.getText() + "' WHERE kode_mutasi = '" + txtKd.getText() + "'";
                st.executeUpdate(SQL);
                String SQLUp = "UPDATE jabatan SET tempat = '" + txtTempat.getText() + "', ruangan = '" + txtRuang.getText() + "' WHERE nip = '" + cbNIP.getSelectedItem() + "'";
                st.executeUpdate(SQLUp);
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                setEmpty();
                setData(MySQL);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try{
            if ((txtKd.getText().equals(""))){
                JOptionPane.showMessageDialog(null, "Pilih Kode Mutasi  Di Tabel");
            }else{
                if (JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus Data Dengan ID "+txtKd.getText()+"", "Confrim", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION) {
                    try{
                        st = con.createStatement();
                        String SQL = "DELETE FROM mutasi WHERE kode_mutasi = '" + txtKd.getText() + "'";
                        st.executeUpdate(SQL);
                        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                        setEmpty();
                        setData(MySQL);
                    }catch (Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        } catch (Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari2ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtCari.getText().trim().equalsIgnoreCase("")){
            }else{
                String SQL = "SELECT * from mutasi WHERE kode_mutasi LIKE '%"+txtCari.getText()+"%' OR nip_karyawan like '%"+txtCari.getText()+"%' OR nama_karyawan like '%"+txtCari.getText()+"%' OR tempat_before like '%"+txtCari.getText()+"%' OR ruangan_before like '%"+txtCari.getText()+"%' OR tempat_after like '%"+txtCari.getText()+"%' OR ruangan_after like '%"+txtCari.getText()+"%' ";
                setData(SQL);
            }
        } catch (Exception e) {
            Logger.getLogger(FormMutasi.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnCari2ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        setEmpty();
        setData(MySQL);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new FormMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtKdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKdActionPerformed

    private void cbNIPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNIPItemStateChanged
        // TODO add your handling code here:
        cbNama.setSelectedIndex(cbNIP.getSelectedIndex());
        cbTempat.setSelectedIndex(cbNIP.getSelectedIndex());
        cbRuangan.setSelectedIndex(cbNIP.getSelectedIndex());
    }//GEN-LAST:event_cbNIPItemStateChanged

    private void cbNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNIPActionPerformed

    private void cbNamaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNamaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNamaItemStateChanged

    private void cbNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNamaActionPerformed

    private void tabelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUserMouseClicked
        // TODO add your handling code here:
        txtKd.setText(tabelUser.getValueAt(tabelUser.getSelectedRow(), 0).toString());
        cbNIP.setSelectedItem(tabelUser.getValueAt(tabelUser.getSelectedRow(), 1).toString());
        cbNama.setSelectedItem(tabelUser.getValueAt(tabelUser.getSelectedRow(), 2).toString());
        cbTempat.setSelectedItem(tabelUser.getValueAt(tabelUser.getSelectedRow(), 3).toString());
        cbRuangan.setSelectedItem(tabelUser.getValueAt(tabelUser.getSelectedRow(), 4).toString());
        txtTempat.setText(tabelUser.getValueAt(tabelUser.getSelectedRow(), 5).toString());
        txtRuang.setText(tabelUser.getValueAt(tabelUser.getSelectedRow(), 6).toString());
    
    }//GEN-LAST:event_tabelUserMouseClicked

    private void cbTempatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTempatItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTempatItemStateChanged

    private void cbTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTempatActionPerformed

    private void cbRuanganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRuanganItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRuanganItemStateChanged

    private void cbRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRuanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMutasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMutasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMutasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMutasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMutasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari2;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbNIP;
    private javax.swing.JComboBox<String> cbNama;
    private javax.swing.JComboBox<String> cbRuangan;
    private javax.swing.JComboBox<String> cbTempat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tabelUser;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKd;
    private javax.swing.JTextField txtRuang;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables
}
